"""Tests for Hermes Web Dashboard (DIM-234).

This suite validates the web shell contract used by the React/TanStack frontend:
- /dashboard host page delivery
- client-side route fallback
- static dashboard assets
- auth boundaries for API routes
"""

import asyncio
import pytest
import base64
import threading
from fastapi.testclient import TestClient
from starlette.websockets import WebSocketDisconnect

# Import after ensuring path
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.main import app
from app import main as main_module
from app.models.schemas import MemoryIngestResponse, SystemStatus, TailscaleInfo


@pytest.fixture
def client():
    """Create a test client for the FastAPI app."""
    return TestClient(app)


def _bearer_auth_header() -> dict[str, str]:
    return {"Authorization": f"Bearer {main_module.settings.bearer_token}"}


class TestDashboardRouting:
    """Dashboard routing and host page tests."""

    def test_dashboard_root_endpoint(self, client):
        """Test that /dashboard returns the host HTML page."""
        response = client.get("/dashboard")
        assert response.status_code == 200
        assert "text/html" in response.headers["content-type"]
        assert "Hermes Mission Control" in response.text
        assert '<div id="root"></div>' in response.text

    def test_dashboard_client_route_fallback(self, client):
        """Test that nested dashboard routes resolve to the same host page."""
        response = client.get("/dashboard/cron")
        assert response.status_code == 200
        assert "text/html" in response.headers["content-type"]
        assert '<div id="root"></div>' in response.text

    def test_dashboard_slash_endpoint_redirects(self, client):
        """Test that / redirects to the dashboard host page."""
        response = client.get("/", follow_redirects=False)
        assert response.status_code == 307
        assert response.headers["location"] == "/dashboard"


class TestDashboardAssets:
    """Static assets generated by Vite should be served by FastAPI."""

    def test_static_css_served(self, client):
        """Test that dashboard CSS is available."""
        response = client.get("/static/css/dashboard.css")
        assert response.status_code == 200
        assert "text/css" in response.headers["content-type"]
        css = response.text
        assert ".instance-switcher" in css
        assert ".cards-grid" in css

    def test_static_js_served(self, client):
        """Test that dashboard JS bundle is available."""
        response = client.get("/static/js/dashboard.js")
        assert response.status_code == 200
        assert "javascript" in response.headers["content-type"]
        js = response.text
        assert len(js) > 200
        assert "/api${path}" in js
        assert '/status?instance=' in js
        assert "/cron?instance=" in js
        assert "toast-container" in js

    def test_dashboard_assets_linked_in_host_html(self, client):
        """Test that host page includes built dashboard assets."""
        response = client.get("/dashboard")
        html = response.text

        assert 'href="/static/css/dashboard.css?v=' in html
        assert 'src="/static/js/dashboard.js?v=' in html


class TestAuthMiddleware:
    """Auth middleware behavior around dashboard integration."""

    def test_dashboard_html_is_public(self, client):
        """Test that /dashboard can be fetched without auth."""
        response = client.get("/dashboard")
        assert response.status_code == 200
        assert "text/html" in response.headers["content-type"]

    def test_dashboard_cloudflare_mode_requires_cf_headers(self, client, monkeypatch):
        """Cloudflare dashboard mode should deny requests without Access headers."""
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "cloudflare")
        monkeypatch.setattr(main_module.settings, "dashboard_shared_secret", None)
        monkeypatch.setattr(main_module, "_request_is_loopback", lambda request: False)
        response = client.get("/dashboard")
        assert response.status_code == 401
        assert response.json()["detail"] == "Dashboard access denied"

    def test_dashboard_cloudflare_mode_allows_loopback_requests(self, client, monkeypatch):
        """Cloudflare dashboard mode should still allow localhost browser access."""
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "cloudflare")
        monkeypatch.setattr(main_module.settings, "dashboard_shared_secret", None)
        monkeypatch.setattr(main_module, "_request_is_loopback", lambda request: True)
        response = client.get("/dashboard")
        assert response.status_code == 200
        assert "text/html" in response.headers["content-type"]

    def test_root_cloudflare_mode_requires_cf_headers(self, client, monkeypatch):
        """Cloudflare dashboard mode should deny root redirects without Access headers."""
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "cloudflare")
        monkeypatch.setattr(main_module.settings, "dashboard_shared_secret", None)
        monkeypatch.setattr(main_module, "_request_is_loopback", lambda request: False)
        response = client.get("/", follow_redirects=False)
        assert response.status_code == 401
        assert response.json()["detail"] == "Dashboard access denied"

    def test_dashboard_cloudflare_mode_accepts_access_identity(self, client, monkeypatch):
        """Cloudflare dashboard mode should allow Access-authenticated requests."""
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "cloudflare")
        monkeypatch.setattr(main_module.settings, "dashboard_shared_secret", None)
        response = client.get(
            "/dashboard",
            headers={"CF-Access-Authenticated-User-Email": "ops@example.com"},
        )
        assert response.status_code == 200

    def test_dashboard_cloudflare_mode_enforces_shared_secret(self, client, monkeypatch):
        """When configured, shared secret is required for dashboard access."""
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "cloudflare")
        monkeypatch.setattr(main_module.settings, "dashboard_shared_secret", "secret-1")
        monkeypatch.setattr(main_module, "_request_is_loopback", lambda request: False)
        response = client.get(
            "/dashboard",
            headers={"CF-Access-Authenticated-User-Email": "ops@example.com"},
        )
        assert response.status_code == 401

        response = client.get(
            "/dashboard",
            headers={
                "CF-Access-Authenticated-User-Email": "ops@example.com",
                "X-Hermes-Origin-Secret": "secret-1",
            },
        )
        assert response.status_code == 200

    def test_dashboard_bearer_mode_requires_api_token(self, client, monkeypatch):
        """Bearer dashboard mode should protect dashboard endpoints."""
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "bearer")
        monkeypatch.setattr(main_module.settings, "dashboard_shared_secret", None)
        monkeypatch.setattr(main_module, "_request_is_loopback", lambda request: False)
        response = client.get("/dashboard")
        assert response.status_code == 401

        response = client.get(
            "/dashboard",
            headers=_bearer_auth_header(),
        )
        assert response.status_code == 200

    def test_mutating_api_still_requires_auth(self, client):
        """Test dashboard changes did not bypass API auth for POST routes."""
        response = client.post("/api/chat", json={"message": "ping", "stream": False})
        assert response.status_code == 401
        assert response.json()["detail"] == "Missing or invalid authorization header"

    def test_memory_ingest_observability_requires_bearer(self, client):
        """Ingest metrics/dead-letter/health GETs should not be public."""
        response = client.get("/api/memory/ingest/metrics")
        assert response.status_code == 401
        assert response.json()["detail"] == "Missing or invalid authorization header"

    def test_memory_ingest_observability_accepts_bearer(self, client):
        """Bearer-authenticated ingest observability requests should pass middleware."""
        response = client.get(
            "/api/memory/ingest/metrics",
            headers=_bearer_auth_header(),
        )
        assert response.status_code == 200

    def test_memory_ingest_offloads_sync_service_from_running_event_loop(self, client, monkeypatch):
        """Ingest should run in a worker thread so sync Hindsight wrappers do not hit nested-loop errors."""

        class FakeService:
            def authenticate_request(self, **kwargs):
                return None

            def ingest(self, events):
                try:
                    loop = asyncio.get_event_loop()
                except RuntimeError:
                    loop = asyncio.new_event_loop()
                    asyncio.set_event_loop(loop)
                assert threading.current_thread() is not threading.main_thread()
                loop.run_until_complete(asyncio.sleep(0))
                return MemoryIngestResponse(
                    accepted=len(events),
                    duplicates=0,
                    dead_lettered=0,
                    transient_failures=0,
                    checkpoints=[],
                    results=[],
                )

        monkeypatch.setattr("app.api.memory_ingest.get_memory_ingest_service", lambda: FakeService())
        response = client.post(
            "/api/memory/ingest",
            headers={
                "X-Hermes-Timestamp": "1712870400",
                "X-Hermes-Nonce": "nonce-test-12345",
                "X-Hermes-Signature": "sha256=dummy",
            },
            json={
                "events": [
                    {
                        "event_id": "evt-1",
                        "source_peer": "pi",
                        "seq": 1,
                        "ts": "2026-04-12T00:00:00Z",
                        "type": "user_message",
                        "payload": {"content": "test"},
                        "payload_hash": "abc",
                    }
                ]
            },
        )
        assert response.status_code == 200
        assert response.json()["accepted"] == 1

    def test_auth_mode_all_rejects_unauthenticated_read(self, client, monkeypatch):
        """AUTH_MODE=all should require auth even for read API routes."""
        monkeypatch.setattr(main_module.settings, "auth_mode", "all")
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "public")
        response = client.get("/api/status")
        assert response.status_code == 401
        assert response.json()["detail"] == "Missing or invalid authorization header"

    def test_auth_mode_all_allows_authenticated_read(self, client, monkeypatch):
        """AUTH_MODE=all should allow read API routes with valid bearer auth."""
        monkeypatch.setattr(main_module.settings, "auth_mode", "all")
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "public")
        response = client.get("/api/status", headers=_bearer_auth_header())
        assert response.status_code == 200

    def test_status_endpoint_accepts_instance_query(self, client, monkeypatch):
        """Status endpoint should pass instance selection through to the monitor."""

        def fake_get_system_status(instance="all"):
            return SystemStatus(
                requested_instance=instance,
                resolved_instance="pi" if instance == "pi" else "pc",
                source_label="test-source",
                cpu_usage=12.5,
                memory_used=100,
                memory_total=200,
                disk_used=300,
                disk_total=400,
                services=[],
                tailscale=TailscaleInfo(funnel=False, hostname="test", ip=None),
            )

        monkeypatch.setattr("app.api.status.system_monitor.get_system_status", fake_get_system_status)
        response = client.get("/api/status?instance=pi", headers=_bearer_auth_header())
        assert response.status_code == 200
        payload = response.json()
        assert payload["requested_instance"] == "pi"
        assert payload["resolved_instance"] == "pi"
        assert payload["source_label"] == "test-source"

    def test_status_endpoint_surfaces_pi_fetch_errors(self, client, monkeypatch):
        """PI telemetry errors should return a 503 instead of masquerading as local status."""
        monkeypatch.setattr(
            "app.api.status.system_monitor.get_system_status",
            lambda instance="all": (_ for _ in ()).throw(RuntimeError("PI telemetry endpoint is not configured")),
        )
        response = client.get("/api/status?instance=pi", headers=_bearer_auth_header())
        assert response.status_code == 503
        assert response.json()["detail"] == "PI telemetry endpoint is not configured"

    def test_auth_mode_all_allows_cloudflare_access_read(self, client, monkeypatch):
        """AUTH_MODE=all should allow API reads when Cloudflare Access headers are trusted."""
        monkeypatch.setattr(main_module.settings, "auth_mode", "all")
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "cloudflare")
        monkeypatch.setattr(main_module.settings, "dashboard_shared_secret", "secret-1")
        response = client.get(
            "/api/status",
            headers={
                "CF-Access-Authenticated-User-Email": "ops@example.com",
                "X-Hermes-Origin-Secret": "secret-1",
            },
        )
        assert response.status_code == 200

    def test_auth_mode_all_allows_cloudflare_access_write(self, client, monkeypatch):
        """Cloudflare-authenticated API requests should pass auth middleware for mutating methods."""
        monkeypatch.setattr(main_module.settings, "auth_mode", "all")
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "cloudflare")
        monkeypatch.setattr(main_module.settings, "dashboard_shared_secret", "secret-1")
        response = client.post(
            "/api/does-not-exist",
            headers={
                "CF-Access-Authenticated-User-Email": "ops@example.com",
                "X-Hermes-Origin-Secret": "secret-1",
            },
        )
        assert response.status_code == 404

    def test_auth_mode_all_rejects_cloudflare_api_auth_without_shared_secret(self, client, monkeypatch):
        """Cloudflare API trust path should work on loopback-only origin paths without shared secret."""
        monkeypatch.setattr(main_module.settings, "auth_mode", "all")
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "cloudflare")
        monkeypatch.setattr(main_module.settings, "dashboard_shared_secret", None)
        monkeypatch.setenv("MC_HOST", "127.0.0.1")
        response = client.get(
            "/api/status",
            headers={"CF-Access-Authenticated-User-Email": "ops@example.com"},
        )
        assert response.status_code == 200

    def test_operations_stream_websocket_requires_token(self, client):
        """WebSocket operations stream should reject unauthenticated clients."""
        with pytest.raises(WebSocketDisconnect) as exc:
            with client.websocket_connect("/api/operations/stream"):
                pass
        assert exc.value.code == 1008

    def test_operations_stream_websocket_accepts_token(self, client, monkeypatch):
        """WebSocket operations stream accepts auth token via query parameter."""
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "public")
        token = main_module.settings.bearer_token
        with client.websocket_connect(f"/api/operations/stream?token={token}") as websocket:
            websocket.send_text("ping")
            payload = websocket.receive_json()
        assert payload["type"] == "ack"
        assert payload["data"] == "ping"

    def test_operations_stream_websocket_accepts_subprotocol_token(self, client, monkeypatch):
        """WebSocket operations stream accepts auth token via subprotocol."""
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "public")
        encoded = base64.urlsafe_b64encode(main_module.settings.bearer_token.encode("utf-8")).decode("ascii").rstrip("=")
        subprotocols = ["hermes-ops.v1", f"hermes-auth.{encoded}"]
        with client.websocket_connect("/api/operations/stream", subprotocols=subprotocols) as websocket:
            websocket.send_text("ping")
            payload = websocket.receive_json()
            accepted_subprotocol = websocket.accepted_subprotocol
        assert payload["type"] == "ack"
        assert payload["data"] == "ping"
        assert accepted_subprotocol == "hermes-ops.v1"

    def test_operations_stream_websocket_accepts_cloudflare_access_on_loopback(self, client, monkeypatch):
        """Loopback-only Cloudflare Access traffic should be enough for browser websocket auth."""
        monkeypatch.setattr(main_module.settings, "dashboard_auth_mode", "cloudflare")
        monkeypatch.setattr(main_module.settings, "dashboard_shared_secret", None)
        monkeypatch.setenv("MC_HOST", "127.0.0.1")
        with client.websocket_connect(
            "/api/operations/stream",
            headers={"CF-Access-Authenticated-User-Email": "ops@example.com"},
        ) as websocket:
            websocket.send_text("ping")
            payload = websocket.receive_json()
        assert payload["type"] == "ack"
        assert payload["data"] == "ping"


class TestMissionControlChat:
    def test_chat_endpoint_returns_stateful_metadata(self, client, monkeypatch):
        class FakeChatService:
            async def send_message(self, message, session_id=None):
                return main_module.chat.ChatResponse(
                    response=f"handled: {message}",
                    type="text",
                    session_id=session_id or "mc_test",
                    model="test-model",
                    provider="test-provider",
                    base_url="https://example.invalid/v1",
                    message_count=2,
                )

        monkeypatch.setattr("app.api.chat.get_chat_service", lambda: FakeChatService())
        response = client.post(
            "/api/chat",
            headers=_bearer_auth_header(),
            json={"message": "ping", "stream": False, "session_id": "mc_test"},
        )
        assert response.status_code == 200
        payload = response.json()
        assert payload["response"] == "handled: ping"
        assert payload["session_id"] == "mc_test"
        assert payload["model"] == "test-model"
        assert payload["message_count"] == 2

    def test_chat_session_endpoint_returns_transcript(self, client, monkeypatch):
        class FakeChatService:
            async def get_session(self, session_id):
                return main_module.chat.ChatSessionResponse(
                    session_id=session_id,
                    model="test-model",
                    provider="test-provider",
                    base_url="https://example.invalid/v1",
                    message_count=2,
                    messages=[
                        {"role": "user", "content": "hi"},
                        {"role": "assistant", "content": "hello"},
                    ],
                )

        monkeypatch.setattr("app.api.chat.get_chat_service", lambda: FakeChatService())
        response = client.get(
            "/api/chat/session/mc_test",
            headers=_bearer_auth_header(),
        )
        assert response.status_code == 200
        payload = response.json()
        assert payload["session_id"] == "mc_test"
        assert payload["message_count"] == 2
        assert payload["messages"][0]["role"] == "user"


class TestDashboardHostStructure:
    """Host page should keep basic accessibility and bootstrap structure."""

    def test_lang_attribute(self, client):
        """Test that HTML has lang attribute."""
        response = client.get("/dashboard")
        html = response.text
        assert '<html lang="en">' in html

    def test_viewport_meta_tag(self, client):
        """Test that viewport meta tag is present for mobile."""
        response = client.get("/dashboard")
        html = response.text
        assert 'name="viewport"' in html
        assert "width=device-width" in html

    def test_noscript_notice_present(self, client):
        """Test that host page includes a noscript notice."""
        response = client.get("/dashboard")
        html = response.text
        assert "requires JavaScript enabled" in html


class TestResponsiveStyles:
    """Dashboard CSS should include responsive breakpoints."""

    def test_css_media_queries_present(self, client):
        """Test that CSS contains media queries for responsiveness."""
        response = client.get("/static/css/dashboard.css")
        css = response.text

        assert "@media (max-width: 1024px)" in css
        assert "@media (max-width: 768px)" in css
        assert "@media (max-width: 480px)" in css


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
